version: '3'
services:
  nuxt:
    container_name: nuxt
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app:cached
      # exclude volumes
      - /app/node_modules
    tty: true
    stdin_open: true
    working_dir: /app
    command: npm run dev
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true
